name: Build and Deploy

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - psycopg2-commit
      - psycopg3-commit

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install
        run: make setup

      - name: Build
        run: make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: master
          folder: build
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: psycopg/psycopg.github.io
